:GUID: %guid%
:OSP_DOMAIN: dynamic.opentlc.com
:GITLAB_URL: %gitlab_url%
:GITLAB_USERNAME: %gitlab_username%
:GITLAB_PASSWORD: %gitlab_password%
:TOWER_URL: %tower_url%
:TOWER_ADMIN_USER: %tower_admin_user%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:VSCODE_UI_URL: %vscode_ui_url%
:VSCODE_UI_PASSWORD: %vscode_ui_password%
:organization_name: Default
:gitlab_project: ansible/gitops-lab
:project_prod: Project gitOps - Prod
:project_test: Project gitOps - Test
:inventory_prod: GitOps inventory - Prod Env
:inventory_test: GitOps inventory - Test Env
:credential_machine: host_credential
:credential_git: gitlab_credential
:credential_git_token: gitlab_token 
:credential_openstack: cloud_credential
:jobtemplate_prod: App deployer - Prod Env
:jobtemplate_test: App deployer - Test Env
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

=== Accessing your Environmet

== Overview

The lab environment consists of the systems shown here:

[options=header,cols="2,1"]
|====
|Host Name |Description
|`control.{GUID}.{OSP_DOMAIN}`    | Ansible Control Node with `ssh` access
|`tower.{GUID}.{OSP_DOMAIN}`      | Ansible Tower Server
|`frontend.{GUID}.{OSP_DOMAIN}`   | Exposed instance for HAProxy Load Balancer
|`app1.{GUID}.{OSP_DOMAIN}`       | Internal App Server for Python/Flask API and Web Site
|`app1.{GUID}.{OSP_DOMAIN}`       | Internal App Server for Python/Flask API and Web Site
|`appdb1.{GUID}.{OSP_DOMAIN}`     | Internal Postgresql Server
|====

== Environment Access
=== Set Up SSH

You must have an SSH connection to your environment.
To access your control system via SSH, use your personal OPENTLC SSO
username and public SSH key.

[NOTE]
Unless noted otherwise, you cannot use SSH to connect directly as `root`.
If you have not already done so, you must provide a public SSH key.
. Go to the link:https://www.opentlc.com/account/[OPENTLC Account Management page^] and click *Update SSH Key*
. Paste your public key in the appropriate field.

[TIP]
For more information on generating an SSH key, see link:https://www.opentlc.com/ssh.html[Setting Up an SSH Key Pair^]

=== SSH into System

Use SSH to remotely connect to the lab control host using your private SSH key,
OPENTLC SSO username, and personal GUID:

+
[source,bash,subs="attributes,verbatim"]
----
$ {SSH_COMMAND} -i path-to-your-ssh-key
----

=== Become Devops User

The Devops User has full ssh capabilities into the other systems in the environment as needed.

After successfully logging in to the control node, become the `devops` user:

+
[source,bash,subs="attributes,verbatim"]
----
$ sudo su - devops
----



=== Explore your environment

Take a few moments to explore your environment and setup up tools, shells, packages you like to use.
You are on a Red Linux 7 control node, like many real world customers, with `ansible` and other tools and utilities installed.
In this section you will:

* Explore the installed Ansible environment and configuration
* Validate Ansible can work with the lab infrastucture

. If you are not already logged in as the `control` node's `devops` service account user, `sudo` to that account.

+
[source,bash]
----
[my-user@control 0 ~]$ sudo su - devops
----
+

.Sample Output
[source,texinfo]
----
Last login: Tue Oct 27 14:46:37 EDT 2020 on pts/0
[devops@control 0 ~]$
----

. Explore your `ansible` setup

+
[source,bash]
----
[devops@control 0 ~]$ ansible --version
----
+

.Sample Output
[source,bash]
----
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/devops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
----
+

Whilst this is the current, supported version, of `ansible` at this writing we'll want something more cutting edge to fully
explore `collections` later.

. Explore your lab environment
+

[source,sh]
----
[devops@control 0 ~]$ ansible all --list-hosts
----
+

.Sample Output
[source,texinfo]
----

  hosts (5):
    app1.example.com
    app2.example.com
    appdb1.example.com
    frontend1.example.com
    tower.example.com
----

. Check you have a working `ssh` config and that `ansible` can connect
+

[source,bash]
----
[devops@control 0 ~] $ ansible all -m ping
----
+

.Sample Output
[source,texinfo]
----
app1.example.com | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
appdb1.example.com | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}

... <TRUNCATED>
----

In the next section we will create and work with our first Collection.
